# Generated by Django 5.0.2 on 2025-04-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('correo', models.EmailField(max_length=254, verbose_name='correo')),
                ('telefono', models.CharField(max_length=15, verbose_name='teléfono')),
                ('asunto', models.CharField(max_length=50, verbose_name='asunto')),
                ('mensaje', models.CharField(max_length=350, verbose_name='mensaje')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
